---
- name: ACL Playbook
  hosts: all
  gather_facts: no
  connection: local
  vars:
    api:
      host: "{{ ansible_host }}"
      username: admin
      password: Cisco123
      transport: nxapi

  tasks:

    - name: Configure test ACL
      nxos_config:
        lines:
          - 10 permit ip 1.1.1.1/32 any log
          - 20 permit ip 2.2.2.2/32 any log
          - 30 permit ip 3.3.3.3/32 any log
          - 40 permit ip 4.4.4.4/32 any log
          - 50 permit ip 5.5.5.5/32 any log
        parents: ip access-list test
        before: no ip access-list test
        match: exact
        provider: "{{ api }}"