---
- name: Create ACL
  hosts: leaf
  gather_facts: no
  connection: local
  vars:
    nxapi:
      host: "{{ ansible_host }}"
      username: admin
      password: Cisco123
      transport: nxapi

  tasks:
  
    #############################################################
    # Create ACL
    #############################################################
    - name: Add sequence 10
      nxos_acl: 
        name: chocker
        seq: 10
        action: deny
        proto: ip
        src: 11.11.11.0/24 
        dest: 12.12.12.0/24 
        provider: "{{ nxapi }}"

    - name: Add sequence 20
      nxos_acl: name=chocker seq=20 action=permit proto=ip src=11.11.12.0/24 dest=any provider="{{ nxapi }}"

    
    #############################################################
    # APPLY ACL TO AN INTERFACE
    #############################################################

#    - name: apply ACL ON SVI 11
#      nxos_acl_interface: name=deny-all interface=eth1/1 direction=ingress state=present provider={{ nxapi }}