---
- name: ACL Playbook
  hosts: all
  gather_facts: no
  connection: local
  vars_files: 
    - secrets.yml

  tasks:

    - name: Exec Command
      nxos_command:
        commands:
          - "{{ command }}"
        provider: "{{ nxapi }}"
      register: output
   
    - debug: var=output.stdout_lines
