---
- name: Snapshot Playbook
  hosts: leaf
  gather_facts:  no
  connection: local
  vars_files: 
    - secrets.yml


  tasks:

    - name: Create a snapshot
      nxos_snapshot:
        action: delete_all
        provider: "{{ nxapi }}"