---
- name: Test Playbook
  hosts: all
  gather_facts: no
  connection: local
  vars_files: 
    - secrets.yml
    
  tasks:
    
    - name: Apply basic template
      nxos_config:
        src: basic.j2
        provider: "{{ nxapi }}"

    - name: Enable NX-API
      nxos_config:
        src: nxapi.j2
        provider: "{{ nxapi }}"
      tags: nxapi



