
    - name: Enable Necessary Spine Features
      nxos_feature:
        feature: "{{item.feature }}"
        provider: "{{ provider }}"
      with_items: "{{ features }}"
      tags: features


    - name: Configure Interfaces
      nxos_interface:
        interface: "{{item.interface }}"
        mode: layer3
        provider: "{{ provider }}"
      with_items:
      - "{{ interfaces }}"
      - "{{ loopbacks }}"
      tags: interfaces

    - name: Configure Interface IP Information
      nxos_ip_interface:
        interface: "{{ item.interface }}"
        addr: "{{ item.addr }}"
        mask: "{{ item.mask }}"
        provider: "{{ provider }}"
      with_items: 
      - "{{ interfaces }}"
      - "{{ loopbacks }}"
      tags: interfaces

    - name: Enable Interface BFD
      nxos_config: 
        lines: 
          - bfd interval 50 min_rx 50 multiplier 3
        parents: "interface {{ item.interface }}"
        provider: "{{ provider }}"
      with_items: "{{ interfaces }}"
      tags: interfaces

    - name: CHANGE INTERFACES MTU TO 9216
      nxos_mtu: 
        mtu: 9216
        interface: "{{ item.interface }}"
        state: present
        provider: "{{ provider }}"
      with_items: "{{ interfaces }}"
      tags: interfaces

    - name: ENABLE NV OVERLAY EVPN
      nxos_evpn_global:
        nv_overlay_evpn: true
        provider: "{{ provider }}"
      tags: vxlan

   # - name: ENSURE BGP ASN EXISTS
   #   nxos_bgp:
   #     asn: "{{ asn }}"
   #     router_id: "{{ router_id }}"
   #     provider: "{{ provider }}"
   #     state: present
   #   tags: bgp

    - name: Apply BGP Template
      nxos_config:
        src: bgp.j2
        provider: "{{ provider }}"
      tags: bgp

    - name: Configure BGP Neighbors
      nxos_config:
        lines:
          - inherit peer ebgp_evpn
          - remote-as {{ item.remote_as }}
        parents: 
          - router bgp {{ asn }} 
          - "neighbor {{ item.neighbor }}"
        provider: "{{ provider }}"
      with_items: "{{ bgp_neighbors }}"
      tags: bgp

    - name: Configure IP Multicast Template
      nxos_config:
        src: multicast.j2
        provider: "{{ provider }}"
      tags: multicast

    - name: Enable IP PIM Spare-Mode on Interfaces
      nxos_config: 
        lines: 
          - ip pim sparse-mode
        parents: "interface {{ item.interface }}"
        provider: "{{ provider }}"
      with_items: "{{ interfaces }}"
      tags: multicast



