---
asn: 65500.1
router_id: 1.0.0.7

interfaces:
  - { interface: Ethernet1/49, addr: 1.1.1.1, mask: 30 }
  - { interface: Ethernet1/50, addr: 1.2.1.1, mask: 30 }
  - { interface: Ethernet1/51, addr: 1.3.1.1, mask: 30 }
  - { interface: Ethernet1/52, addr: 1.4.1.1, mask: 30 }
  - { interface: Ethernet2/49, addr: 1.5.1.1, mask: 30 }
  - { interface: Ethernet2/50, addr: 1.6.1.1, mask: 30 }

loopbacks:
  - { interface: loopback0, addr: 1.0.0.7, mask: 32 }
  - { interface: loopback1, addr: 2.0.0.7, mask: 32 }

mgmt:
  - { interface: mgmt0, addr: 10.83.11.64, mask: 24 }

bgp_neighbors:
  - { remote_as: 65500.12, neighbor: 1.1.1.2, update_source: Loopback0 }
  - { remote_as: 65500.12, neighbor: 1.2.1.2, update_source: Loopback0 }
  - { remote_as: 65500.34, neighbor: 1.3.1.2, update_source: Loopback0 }
  - { remote_as: 65500.34, neighbor: 1.4.1.2, update_source: Loopback0 }
  - { remote_as: 65500.56, neighbor: 1.5.1.2, update_source: Loopback0 }
  - { remote_as: 65500.56, neighbor: 1.6.1.2, update_source: Loopback0 }